# Generated by Django 3.2.14 on 2022-07-20 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=20, unique=True)),
                ('explain', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user_id', models.ForeignKey(db_column='create_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='newword', to=settings.AUTH_USER_MODEL)),
                ('like_user_ids', models.ManyToManyField(related_name='likeword', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
