# Generated by Django 3.2.14 on 2022-07-20 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newword',
            name='like_user_ids',
            field=models.ManyToManyField(blank=True, related_name='likeword', to=settings.AUTH_USER_MODEL),
        ),
    ]
