# Generated by Django 4.0.6 on 2022-07-22 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_newword_like_user_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='newword',
            name='likeCnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newword',
            name='create_user_id',
            field=models.ForeignKey(db_column='create_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='newword', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
